### ISSUE TITLE
Emerald pickaxe isn't valid for breaking obsidian

### ISSUE THREAD

**Issue by PurpleHel** [grim3212/AssortedTools#10]
1.16.4, tools 2.2.9. When I go to try to break obsidian with the emerald pickaxe, the obsidian won't break. Emerald is higher than diamond, so it ought to work.

**Comment by grim3212** [comment]
Alright I have updated it, though you will need to delete the config for it to be picked up as I just changed the default harvest level so it won't update unless the config is changed.

**Comment by PurpleHel** [comment]
Cool, thanks!
