### ISSUE TITLE
[1.16.5][Suggestion/Request] Shears, Enchantment on stuff, New tool, small bug

### ISSUE THREAD

**Issue by drakray** [grim3212/AssortedTools#12]
Shears, of all Assorted Material(like Multitools)
-Make the shears drop stuff correctly, like (modded)leaves and Cobweb (a lot of modded shears don't)

Enchantment on tool:
- Multitools:
  - Comb Cutter (from The Bumblezone, normally available on Shears and Swords)
  - Looting (Multitools is a sword)
- Mining Wand
  - Fortune (useful with 'Surface Mining', which is not OP enough XD )

Maybe a way to configure/upgrade the wands, for bigger zone, or set a limit by dimension instead of number of block.

New tool:
- Coral Shears
  - Used to get coral without silk tough

Also, small "bug?", but Reinforced Mining Wand says limit is 1024, but cant mine 1024
`Too many block to dig (1024, limit=1024).`
So it's not possible to mine 4 layer of a single chunk

**Comment by grim3212** [comment]
I like the idea of the Shears since I have a lot of the other tools already! That being said I try not to support old versions other than bug fixes so no promises on that, but it definitely is interesting.

Also the enchantments on the Multitool also sound nice to have. That `shouldn't` be too hard.

Not quite sure of enchantments on the wands yet. Though configuration would be a nice to have as the wands are kinda limited in that front right now.

If I add the other shears I will add the Coral Shears in there. Are they just made out of Coral? Is this an enchantment for shears? What do you think.

Also looks like the range is probably off by 1. I can fix that in a future update.

**Comment by drakray** [comment]
I really hope it's simple enough to be worthy of a 1.16.5 port, as my pack is a long way from being updated to 1.18, seeing as Forge a little more than a week old, and most big mods will take a good while to port.

The shears would be to gather coral more easily/early, so maybe just something like shears+diamond in crafting table to make them, as it would defeat the purpose if they need coral to craft, as you would need silk touch already.

Thank you for the consideration and your good work, your mods will always have their spot in my private packs :D

**Comment by grim3212** [comment]
Yeah, that is the main reason why I was considering to bring them to 1.16.5. I am severely limited on time lately so I am still not quite sure when I would have time to do the bigger asks.

And okay that could make sense. I will think about it.

**Comment by drakray** [comment]
No problem, take your time, real life always comes first ;)

**Comment by grim3212** [comment]
Okay in the latest update we have:

- Shears for each material
- A new shear enchantment for being able to harvest Coral
- MultiTools actually supporting any Enchantments that a Sword, Shovel, Pickaxe, Axe, or Hoe can
- Should have fixed the off by one error in the Mining Wands
- Better Buckets should now dispense out of Dispenser's better
- Added a couple missing gold tools to the Piglin loved tag

This should close out most of the changes requested here with what's left just being wand related and possibly porting to 1.16.5. Still haven't decided.

Going to close this issue down feel free to create a new one for the what's left.

**Comment by drakray** [comment]
I personally left 1.16.5, but am now on 1.18.1, since not every mod ported to 1.18.2 since it seems to be not so easy.
I can't wait to try AssortedSuite soon :D

**Comment by grim3212** [comment]
Okay cool! It's pretty annoying that 1.18.1 and 1.18.2 are so different. I hate when that sort of segmentation happens in the same version.

**Comment by drakray** [comment]
I figured, that's why I didn't even ask you if you planned a 1.18.1 version lol
But eh, that's the risk of modding/playing with mods lol

**Comment by grim3212** [comment]
😅, fair enough. Something to look forward to when more mods get a 1.18.2 version.
