### ISSUE TITLE
[1.18.2] Forge 40.0.18 breaks mod

### ISSUE THREAD

**Issue by Baggytrousers27** [grim3212/AssortedTools#13]
Assorted Tools (assortedtools) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

assortedcore-1.18.2-4.0.0
assortedtools-1.18.2-5.2.2
Forge 40.0.18

[Crashlog](https://pastebin.com/YP2pexem)

**Comment by grim3212** [comment]
Fixed with [0a4fcf9](https://github.com/grim3212/AssortedTools/commit/0a4fcf9c25f0624431a2a35ba115d5c9257f6ce8)

Please use `assortedtools-1.18.2-5.2.3` once it has been approved on CurseForge.

**Comment by Baggytrousers27** [comment]
Splendiferous.
