### ISSUE TITLE
crash on dedicated server 1.19.2  when clicking a loot chest

### ISSUE THREAD

**Issue by SDUBZ** [grim3212/AssortedTools#14]
forge:43.2.14
Minecraft:1.19.2
assorted version: assortedtools-1.19.2-6.1.3
all the crash reports link back to assorted tools

[crash-2023-06-13_06.43.29-server.txt](https://github.com/grim3212/AssortedTools/files/11735812/crash-2023-06-13_06.43.29-server.txt)
[crash-2023-06-13_07.02.57-server.txt](https://github.com/grim3212/AssortedTools/files/11735813/crash-2023-06-13_07.02.57-server.txt)

**Comment by SDUBZ** [comment]
this is still happening 
@grim3212 any help or advice ?

[crash-2023-07-11_05.10.01-server.txt](https://github.com/grim3212/AssortedTools/files/12045373/crash-2023-07-11_05.10.01-server.txt)

**Comment by grim3212** [comment]
Sorry, I have been busy and have not been able to get to this. If you are able to upgrade past 1.19.2 those versions should have the fix for this crash. Once I get a chance I will try and backport to 1.19.2

**Comment by SDUBZ** [comment]
sadly this is part of a big modpack and i will just have to wait until you get a update out
but thank you for the check in on the situation

**Comment by grim3212** [comment]
The latest version 6.1.4 should fix this now.

**Comment by SDUBZ** [comment]
just a heads up it downloads fabric api and adds the 1.20 version of assorted lib
you might want to fix that when you get a a chance

**Comment by grim3212** [comment]
Not sure why it tries to download fabric. But th assorted-lib dependency for this should be removed
