### ISSUE TITLE
[Bug?] Chicken Suit can't be used to Chicken Jump Enchant armor anymore

### ISSUE THREAD

**Issue by drakray** [grim3212/AssortedTools#16]
Is this an intended feature?
If so, is it still possible to make the Chicken Jump Enchant other than using the Enchanting Table?

**Comment by grim3212** [comment]
This is not intended so it definitely is a bug.

I attempted to do this on both Fabric/Forge versions on 1.19.4 and 1.20.1 and was able to enchant just fine.
Maybe a recent Forge/Fabric version broke the functionality.

Could you let me know what versions you are using and what exactly you are trying to get enchanted?
Like if you are trying to enchant a Chest Plate are you using the Chicken Suit Chest Plate?

**Comment by drakray** [comment]
Using [NeoForge](https://neoforged.net/) 47.1.65, but this was present before in plain Forge, don't remember which but "recent" version
Yes I tried to enchant using the correct parring
JEI does not show the enchant possibility, which it did before I think?
I tried enchanting vanilla and modded armor this way, didn't work
The Chicken Suit itself work when worn
Using enchanting book on armor also work

I use a lot of mods, maybe a conflict?

**Comment by grim3212** [comment]
Yeah possibly, let me try updating to a newer Forge version and see if I see it break. I'm guessing that's what happened.

**Comment by grim3212** [comment]
I was unable to repro on the latest Forge version (47.1.43). It still works as expected. 
I also tried with the latest NeoForge and it also works as expected.

So it must be a mod conflict.

**Comment by drakray** [comment]
ok I'll test by adding mods 1by1 until it doesn't work

**Comment by drakray** [comment]
I did some tests, and it seems that having 90 loaded mods trigger the inability to merge armor with ChickenArmor.
At 89 loaded mods(as seen in the bottom left of the main menu), merging armor work, but adding one or more mods make the merge in Anvil not available :/
Most of these mods were libraries and technical mods, not even content/blocks/items mods


Also, I found a conflict with PrimalMagic, where adding it to the pack make the chickenArmor or jump-enchanted armor stop responding to the multijump [Space] pressing
Holding [Space] make the armor do quick jumps
The passive slowfall is still working though
There is no key conflict with [Space]
This was tested with minimal mods(assortedSuite(7 mods), JEI and JER) and 220+ mods


JEI shows that it's possible to use the Chicken Jump Enchanted Book to enchant armor pieces, but not using the chickenArmor piece
JER does not list ChickenJump as a valid Enchantment in it's tab either
This was also tested with minimal mods(assortedSuite(7 mods), JEI and JER) and 220+ mods

**Comment by grim3212** [comment]
Updates 😅

- No idea why the number of mods should have any affect on enchantability
- I need to figure out if there is a way to make the chicken jump still work with PrimalMagic at the moment I had no luck

**Comment by grim3212** [comment]
Regarding the PrimalMagick conflict. It looks like we both consume the jump handler so only one of the things will run. I should be able to switch it up to just check for if the jump key is down.

It will need a cooldown now so it will be a bit different but it should allow for them to both work 🤞

I also add a the recipes to JEI. Since you can't add custom anvil recipes like other types it works a bit different which explains why it isn't showing properly.

**Comment by grim3212** [comment]
I'm attempting to see if I can get any indication why enchanting breaks for you. But that may not end up being something I am able to fix 🤷‍♂️

**Comment by grim3212** [comment]
Lol, I think I found the issue. If it is what I am thinking it is pretty dumb. Still confirming

**Comment by grim3212** [comment]
Okay new version is processing now 10.0.3.

This should fix both issues with the conflict and that it just stops working after a certain amount of mods. I never set the load order so it could possibly try to load before AssortedLib which broke things. 😜

**Comment by drakray** [comment]
Work perfectly so far (even though Chicken jump is not listed in JER enchantments tab, which is really no big deal)
the JEI Anvil tab show the usage of the chicken Part on certain modded armor but not all, but the anviling work, so not really a problem either
it's seems to be on the other mod's side, since they don't show some other enchanted book either

Thank you for you good work, really appreciate it, I can't play without your mods anymore XD

**Comment by grim3212** [comment]
Honestly I don't actually know how to get to the enchantments tab. I installed but never saw what you were talking about. 

As for why some armored don't show up under the anvil. It just uses an armors tag to show in jei. If the modded doesn't have each piece tagged then that would be why. You could probably create a data pack to add the tag for the armors that you want to show that are still missing.

Anyway enjoy, sorry it took so long to determine what turned out to be something so simple 🙂

**Comment by drakray** [comment]
Well the JEI/JER stuff is really not important at all lol, it work anyway

Don't be sorry, I know the simpler the cause, the harder the debug XD
