### ISSUE TITLE
[Question] Config for Multitool multiplier?

### ISSUE THREAD

**Issue by drakray** [grim3212/AssortedTools#17]
Hi Grim, how are you?
It's me again XD :P

Quick question, wasn't there a config to set a multiplier for the Multitool durability?
Right now they use the same value as the base tool, and I'd like to bump them up a little, since they cost more

Or maybe I'm just not seeing it lol
I found the maxUses config, but that set the durability of all tools, not just the Multitool(for modded tools, Vanilla override set the multitool only)

**Comment by grim3212** [comment]
Yeah, I thought there was a multiplier but maybe that was just something I had planned.

Not entirely sure when I would get around to adding it. I'm pretty busy as of late.

**Comment by drakray** [comment]
no problem with that take your time, real life is always the priority :D
Thank you for looking into it ^_^

**Comment by grim3212** [comment]
I'm thinking if I make the change it will probably be for 1.20.1 and forward.

I haven't really been paying attention so I feel like most have moved on from 1.19.4?

**Comment by drakray** [comment]
I personally have no problem with that, I'm on 1.20.1 myself :P
I don't think I have played 1.19.4, I went from 1.19.2 to 1.20.1 directly, most of the mods I use skipped .3 and .4

I use NeoForge though, so I don't plan on moving to 1.20.2 soon but that's on me(also almost all of the mods I use are .1, not .2 yet)

**Comment by grim3212** [comment]
I didn't even realize there was a 1.20.2 😅

Looks like neoforge 1.20.2 will no longer be back compatible with Forge. I will probably end up switching to that as well. But no idea when especially since it doesn't look like they even support it yet. 🤷‍♂️


Anyway I have the changes done for this config for the modifier. Just taking a look to see if anything sticks out about the Chicken Suit issue you brought up before publishing a new version. Still not having much luck repro'ing. It seems very odd.

**Comment by drakray** [comment]
I don't know if it can help, but [here](https://www.dropbox.com/scl/fi/x8vydinbu4ccb4w0lla38/Skyblock2.zip?rlkey=fc71au4sogrfyn1zuh1wk5hp2&dl=0) is my custom modPack

**Comment by drakray** [comment]
I use Java-17 from C:\Program Files\Java\jdk-17\bin\javaw.exe
NeoForge 47.1.79
and here is my jvm arguments string:
```
-Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

**Comment by grim3212** [comment]
Thanks, I was definitely able to repro with that. It doesn't really make much sense why that would break.

Also noticed the non-jump conflict as well. That one seems easier to fix 😅

**Comment by drakray** [comment]
I would say it's something to do with some kind of array limit(since it seems related to mod quantity more than mod type), but that doesn't make much sense I think :/

At least it's not a me problem XD(as in, I'm the problem)

**Comment by grim3212** [comment]
New versions are processing for the config. gonna move this conversation back to the other issue.

**Comment by drakray** [comment]
Work perfectly, thanks! (though I had to reset my config because I messed it up lol )
