### ISSUE TITLE
[Suggestion][1.16.3] Chicken Suit enchantment/upgrade

### ISSUE THREAD

**Issue by drakray** [grim3212/AssortedTools#2]
Hi there, a little suggestion/request, if possible

Using the Smithing Table to be able to upgrade the Chicken Suit, of to upgrade any armor with the Chicken Suit Ability
I think, if you put the CS in the left slot, with any other armor piece(of the same slot) in the right, the Chicken Armor could get the stats (durability, generic.armor, generic.armor_toughness)
If the anyArmor is in the left, and CS in the right, the anyArmor would just get the +1 jump and the slowFall, keeping it's stats and other abilities if relevant (NeptuniumArmor from Aquaculture2, for exemple)

Otherwise, maybe just a +1jump enchantment, applicable to any armor pieces, maybe even upgradable to +5jump per piece :D 
LET ME FLY! lol

IF possible at all, that is ;)

What do you think?

**Comment by grim3212** [comment]
Interesting, I honestly didn't know the smithing table existed. Been out of Minecraft for a while of now. Let me see how it would work but I like the idea of getting the other armors stats while retaining the jump. Though for now if I did it, it would keep the normal +1 jump per armor piece. Maybe down the line upgrading it would be possible.

**Comment by grim3212** [comment]
Spent some time looking into this this morning. And the smithing table doesn't seem to allow for much customization, each new armor piece added would need to be its own Item so supporting mod items would be very difficult. I may be able to do it with Anvils as that seems much more flexible. Thoughts?

**Comment by drakray** [comment]
Honestly, it could even be done in the Crafting Table if it's easier/the only way lol
I only suggested the Smithing Table for "roleplay" purpose ;)
The Anvil could work as well

Though maybe the better way would be to make a MultiJump Enchantment instead, probably less trouble than changing the suit's stats, and making the enchanting book craftable with CS piece(doable with CraftTweaker)

**Comment by grim3212** [comment]
I decide to go with the enchantment route as changing the suits stats was getting troublesome. This feels a bit cleaner too. Basically put a piece of armor on the left in the Anvil and the matching chicken suit armor piece and then the armor will get the Chicken Jump enchantment. 

Closed with e797874

**Comment by drakray** [comment]
Perfect, will try it soon™ :D
