### ISSUE TITLE
Add config to disable items

### ISSUE THREAD

**Issue by Skjolbir** [grim3212/AssortedTools#4]
Hi. Love the mods, works really really well.
I am asking though that the config allows us to disable certain items, as the wands are a bit too OP for my SMP server.

**Comment by grim3212** [comment]
Should be closed with d9262d6. It will disable the recipe and from showing up in the Assorted Tools creative tab which seems to be the recommended way of disabling items. It will be up once CurseForge is out of maintenance mode.

**Comment by Skjolbir** [comment]
legend.
