### ISSUE TITLE
MultiTools default damage should be whichever tool materials does the most

### ISSUE THREAD

**Issue by grim3212** [grim3212/AssortedTools#7]
See: https://www.curseforge.com/minecraft/mc-mods/assorted-tools?comment=40

"A multitool of a given material should do as much damage as whichever standard tool of that material does the most, usually the axe, since all the standard tools go into making the multitool. Like, a diamond axe does 9 damage, but the diamond multitool only does 8. That doesn't seem OP to me, just logical."

**Comment by drakray** [comment]
A Multitool Suggestion: could it be possible to upgrade the Diamond Multitool to Netherite in a Smithing Table with a Netherite Block?
It would cost slightly more than going the other way(4 diamond more), which could remain available, but would allow for upgrading later on, mainly useful for enchanted Diamond Multitool(provided enchantment stays on).

**Comment by grim3212** [comment]
Alright both should now be out in the latest release. 👍
