### ISSUE TITLE
Tools are not held in the hand like a tool

### ISSUE THREAD

**Issue by WenXin20** [grim3212/AssortedTools#8]
`Assorted Tools v2.2.6`
`Minecraft v1.16.4`
`Forge v35.1.28`

All tools & weapons, including hammers, wands, boomerangs, & multitools, are not held in the hand in third-person like vanilla tools are.

I also updated the textures of some items & blocks from Assorted Tools & Storage to have the new vanilla style if you would like to use any of them. 
[Assorted Tweaks.zip](https://github.com/grim3212/AssortedTools/files/5758597/Assorted.Tweaks.zip)

![2020-12-31_20 42 38](https://user-images.githubusercontent.com/12000593/103432727-21e34c80-4baa-11eb-9634-d22d00faad11.png)

**Comment by grim3212** [comment]
Cool, thanks for letting me know. I should be able to take a look at this sometime today or tomorrow. I'll let you know.

**Comment by grim3212** [comment]
Alright the latest release of Tools should include the model fixes as well as the texture changes. Those wand textures are very nice! Storage also included your texture updates too.

**Comment by WenXin20** [comment]
Alright, thanks!
